export const SHOW_RECORDING_SCREEN = 'SHOW_RECORDING_SCREEN';
export const SHOW_SHARE_SCREEN = 'SHOW_SHARE_SCREEN';
export const SHOW_MAIN_SCREEN = 'SHOW_MAIN_SCREEN';
export const LIST_MODE_MODEL = 'LIST_MODE_MODEL';
export const LIST_MODE_PORTAL = 'LIST_MODE_PORTAL';
export const LIST_MODE_EFFECT = 'LIST_MODE_EFFECT'
