target 'ViroCodeSamples' do
  pod 'React', :path => '../node_modules/react-viro', :subspecs => [
    'Viro',
    'Core',
    'RCTWebSocket',
    'RCTActionSheet',
    'RCTNetwork',
    'RCTText',
  ]
  pod 'GVRSDK', '1.0.0'

  target 'ViroCodeSamplesTests' do
     inherit! :search_paths
  end
end
