

def required_pods
  # we've got a dependency on ViroKit rather than ViroReact because we want to build ViroReact
  # each time we build ViroExample vs having to build ViroReact, run `npm pack` then `npm install`
  # and then building ViroExample.
  pod 'Fabric', '1.7.2'
  pod 'Crashlytics', '3.9.3'
end

target 'ViroExample' do
  use_frameworks!
  required_pods
  pod 'ViroKit', :path => '../../../ios/dist/ViroRenderer'
end

target 'ViroExample_archive' do
  use_frameworks!
  required_pods
  pod 'ViroKit', :path => '../../../ios/dist/ViroRenderer'
end

target 'ViroExample_no_use_frameworks' do
  required_pods
  pod 'ViroKit_static_lib', :path => '../../../ios/dist/ViroRenderer/static_lib'
end
