# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

default_platform :android

import "../../../../ViroRenderer/android/fastlane/Fastfile"

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end
  desc "Build renderer"
  lane :renderer_aar do
    ensure_git_status_clean
    git_pull
    Dir.chdir("../../../../ViroRenderer/android/") do
      sh("fastlane release_renderer_react_lib")
    end
    changelog_from_git_commits(commits_count: 5,
                   pretty: "- (%ae) %s",
                   date_format: "short",
                   merge_commit_filtering: "exclude_merges")
  end 

  desc "Build GVR release tests"
  lane :gvr_release_test do
    renderer_aar
    gradle(task: "assembleGvrRelease")
  end

  desc "Build OVR release tests"
  lane :ovr_release_test do
    renderer_aar
    gradle(task: "assembleOvrRelease")
  end

  desc "Build GVR & OVR release tests"
  lane :release_test do
    renderer_aar
    gradle(task: "assembleRelease")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
