# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

default_platform :ios
platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Build react, ViroReact frameworks"
  lane :release_react_viro_lib do
    Dir.chdir("../") do
      sh("cp -r /tmp/react_viro_kit/ViroKit.framework/ ../../ios/dist/ViroRenderer/ViroKit.framework/")
       # clean React scheme
       sh("xcodebuild -workspace ViroExample/ViroExample.xcworkspace/ -scheme React -configuration Release clean | xcpretty -c")
       sh("xcodebuild -workspace ViroExample/ViroExample.xcworkspace/ -scheme ViroReact -configuration Release clean | xcpretty -c")
       sh("xcodebuild -workspace ViroExample/ViroExample.xcworkspace/ -scheme ViroExample -configuration Release clean | xcpretty -c")
       # build React scheme
       sh("xcodebuild -workspace ViroExample/ViroExample.xcworkspace/ -scheme React -configuration Release | xcpretty -c")

       # build ViroReact scheme
       sh("xcodebuild -workspace ViroExample/ViroExample.xcworkspace/ -scheme ViroReact -configuration Release | xcpretty -c")

     end
  end

  lane :jenkins_release_tests do
      increment_build_number(
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "./ViroExample/ViroExample.xcodeproj"
      )
      cert
      sigh(force: true)
      gym(scheme: "ViroExample",
                workspace: "./ViroExample/ViroExample.xcworkspace",
                configuration: "Release",
                clean: true,
                output_directory: "./build",
                output_name: "ViroExample.ipa") 
#       pilot(username: "manish@viromedia.com",
#             ipa: "./build/ViroExample.ipa",
#             skip_waiting_for_build_processing: true)
  end

  lane :test do
    Dir.chdir("../") do
      sh("cp -r /tmp/react_viro_kit/ViroKit.framework/ ../../ios/dist/ViroRenderer/ViroKit.framework/")
    end
  end
end
# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
