# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

default_platform :android
# Import ViroRenderer's fastfile
import "../../../ViroRenderer/android/fastlane/Fastfile"

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    ensure_git_status_clean
    git_pull
  end

  desc "Remove current renderer aar, Build renderer, build bridge library aar"
  lane :release_react_bridge do
    gradle(project_dir:"../../ViroRenderer/android/", task:"assembleViro_reactRelease")
    gradle(task: "viro_bridge:assemble")
    sh("cp ../viro_bridge/build/outputs/aar/viro_bridge-release.aar ../react_viro/react_viro-release.aar")
    Dir.chdir("../../") do
      sh("npm pack")
    end
  end 
  
  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
