# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

require 'Fileutils.rb'
default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  lane :gradle_clean_bridge do
    gradle(task: "clean")
  end
  
  lane :release_react_bridge_jenkins do
    sh("rm ../viro_renderer/viro_renderer-release.aar")
    sh("cp /tmp/viro_react_lib/viro_renderer-release.aar ../viro_renderer/")
    gradle(task: "viro_bridge:assemble")
    sh("cp ../viro_bridge/build/outputs/aar/viro_bridge-release.aar ../react_viro/react_viro-release.aar")
  end

  desc "Remove current renderer aar, Build renderer, build bridge library aar"
  lane :release_react_bridge do
    ensure_git_status_clean
    git_pull
    gradle(task:"clean")
    gradle(project_dir:"../../ViroRenderer/android/", task:"assembleViro_reactRelease")
    gradle(task: "viro_bridge:assemble")
    sh("cp ../viro_bridge/build/outputs/aar/viro_bridge-release.aar ../react_viro/react_viro-release.aar")
    Dir.chdir("../../") do
      sh("npm pack")
    end
  end 
  
  lane :upload_builds_and_slack do
    Dir.chdir("/tmp/s3_artifacts") do
     timestamp=Time.now.strftime('%Y-%m-%d_%H-%M-%S')
     sh("aws s3 sync . s3://viro-builds/#{timestamp}/")
     url_virocore=sh("aws s3 presign s3://viro-builds/#{timestamp}/virocore-release-v_1_6_0.aar --expires-in 86400")
     url_tgz=sh("aws s3 presign s3://viro-builds/#{timestamp}/react-viro-2.6.1.tgz --expires-in 86400")
     url_gvr_apk=sh("aws s3 presign s3://viro-builds/#{timestamp}/app-gvr-release.apk --expires-in 86400")
     url_ovr_apk=sh("aws s3 presign s3://viro-builds/#{timestamp}/app-ovr-release.apk --expires-in 86400")
     slack(
           message: ":white_check_mark: Build Pipeline successfully completed and artifacts uploaded to S3.",
           success: true,
           slack_url: "https://hooks.slack.com/services/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",
           payload: {
             "Build Date" => Time.new.to_s,
           },
           attachment_properties: {
              fields: [{
              title: "Last Commit",
              value: "My Value",
              short: true
    }]
  }
       )
    end
  end  
  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
