
import * as LoadingConstants from '../redux/LoadingStateConstants';

var POSITION_OFFSET = .05 // 5 cm

var ModelItems = [
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_happy.png"),
    "obj": require("../res/emoji_smile/emoji_smile.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "position" : [0, .497823 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_smile/emoji_smile_specular.png'),require('../res/emoji_smile/emoji_smile_diffuse.png'), require('../res/emoji_smile/emoji_smile_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_sad.png"),
    "obj": require("../res/emoji_sad/emoji_sad.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "position" : [0, .494890 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_sad/emoji_sad_specular.png'), require('../res/emoji_sad/emoji_sad_diffuse.png'), require('../res/emoji_sad/emoji_sad_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_wow.png"),
    "obj": require("../res/emoji_wow/emoji_wow.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "position" : [0, .494890 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_wow/emoji_wow_specular.png'), require('../res/emoji_wow/emoji_wow_diffuse.png'), require('../res/emoji_wow/emoji_wow_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_angry.png"),
    "obj": require("../res/emoji_angry/emoji_angry.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "position" : [0, .494890 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_angry/emoji_angry_specular.png'), require('../res/emoji_angry/emoji_angry_diffuse.png'), require('../res/emoji_angry/emoji_angry_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_kiss.png"),
    "obj": require("../res/emoji_kiss/emoji_kiss.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "position" : [0, .494890 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_kiss/emoji_kiss_specular.png'), require('../res/emoji_kiss/emoji_kiss_diffuse.png'), require('../res/emoji_kiss/emoji_kiss_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_heart.png"),
    "obj": require("../res/emoji_heart/emoji_heart.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "position" : [0, .451719 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_heart/emoji_heart_specular.png'), require('../res/emoji_heart/emoji_heart.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_thumbsup.png"),
    "obj": require("../res/emoji_thumbsup/emoji_thumbsup.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "position" : [0, 0.506186 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_thumbsup/emoji_thumbsup_specular.png'), require('../res/emoji_thumbsup/emoji_thumbsup_diffuse.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_poop.png"),
    "obj": require("../res/emoji_poop/emoji_poop.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "position" : [0, .353032 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_poop/emoji_poop_specular.png'), require('../res/emoji_poop/emoji_poop_diffuse.png'), require('../res/emoji_poop/emoji_poop_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_star.png"),
    "obj": require("../res/emoji_star/object_star.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.25, .25, .25],
    "position" : [0, .939014 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_star/object_star_specular.png'), require('../res/emoji_star/object_star_diffuse.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_rainbow.png"),
    "obj": require("../res/object_rainbow/object_rainbow.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [1, 1, 1],
    "position" : [0, .235285 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_rainbow/object_rainbow_diffuse.png'), require('../res/object_rainbow/object_rainbow_specular.png')]
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_cloud.png"),
    "obj": require("../res/object_cloud/object_cloud.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [0.3, 0.3, 0.3],
    "position" : [0, .235285 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_cloud/object_cloud_diffuse.png'), require('../res/object_cloud/object_cloud_specular.png')]
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_pug.png"),
    "obj": require("../res/object_pug_animated/pug_animated.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.3, .3, .3],
    "position" : [0, 0, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_pug_animated/pug_body_specular.png'), require('../res/object_pug_animated/pug_body_diffuse.png'), require('../res/object_pug_animated/pug_body_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_cake.png"),
    "obj": require("../res/object_bday_cake/object_bday_cake.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.3, .3, .3],
    "position" : [0, .135234, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_bday_cake/object_cake_specular.png'), require('../res/object_bday_cake/object_cake_diffuse.png'), require('../res/object_bday_cake/object_cake_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_flowers.png"),
    "obj": require("../res/object_flowers/object_flowers.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.6, .6, .6],
    "position" : [0, .290760, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_flowers/object_flowers_specular.png'), require('../res/object_flowers/object_flowers_diffuse.png'), require('../res/object_flowers/object_flowers_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_cube.png"),
    "obj": require("../res/object_cube/object_cube.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.2, .2, .2],
    "position" : [0, .5 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_cube/cube_diffuse.png'), require('../res/object_cube/cube_specular.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_sphere.png"),
    "obj": require("../res/object_sphere/object_sphere.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.15, .15, .15],
    "position" : [0, 1 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_sphere/sphere_diffuse.png'), require('../res/object_sphere/sphere_specular.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_portal_pyramid.png"),
    "obj": require("../res/object_pyramid/object_pyramid.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.25, .25, .25],
    "position" : [0, .7 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_pyramid/pyramid_diffuse.png'), require('../res/object_pyramid/pyramid_specular.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_baseball.png"),
    "obj": require("../res/object_baseball/object_baseball.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [0.25,0.25,0.25],
    "position" : [0, .25 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_baseball/object_baseball_diffuse.png'), require('../res/object_baseball/object_baseball_specular.png'), require('../res/object_baseball/object_baseball_normal.png')],
  },
    {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_basketball.png"),
    "obj": require("../res/object_basketball/object_basketball.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [0.4, 0.4, 0.4],
    "position" : [0, .25 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_basketball/object_basketball_diffuse.png'), require('../res/object_basketball/object_basketball_specular.png'), require('../res/object_basketball/object_basketball_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_soccerball.png"),
    "obj": require("../res/object_soccerball/object_soccer_ball.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [0.4, 0.4, 0.4],
    "position" : [0, .25 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_soccerball/object_soccer_ball_diffuse.png'), require('../res/object_soccerball/object_soccer_ball_specular.png'), require('../res/object_soccerball/object_soccer_ball_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_golfball.png"),
    "obj": require("../res/object_golfball/object_golfball.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [0.25, 0.25, 0.25],
    "position" : [0, .25 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_golfball/object_golfball_diffuse.png'), require('../res/object_golfball/object_golfball_specular.png'), require('../res/object_golfball/object_golfball_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_volleyball.png"),
    "obj": require("../res/object_volleyball/object_volleyball.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [0.25, 0.25, 0.25],
    "position" : [0, .25 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_volleyball/object_volleyball_diffuse.png'), require('../res/object_volleyball/object_volleyball_specular.png'), require('../res/object_volleyball/object_volleyball_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_football.png"),
    "obj": require("../res/object_football/object_football.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [0.25, 0.25, 0.25],
    "position" : [0, .25 + POSITION_OFFSET, 0],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_football/object_football_diffuse.png'), require('../res/object_football/object_football_specular.png'), require('../res/object_football/object_football_normal.png')],
  }
]

module.exports = {
  getModelArray: function() {
    return ModelItems;
  }
};
