
import * as LoadingConstants from '../redux/LoadingStateConstants';

var ModelItems = [
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_happy.png"),
    "obj": require("../res/emoji_smile/emoji_smile.vrx"),
    "materials": null,
    "animation":null,
    "scale": [0.2, 0.2, 0.2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_smile/emoji_smile_specular.png'),require('../res/emoji_smile/emoji_smile_diffuse.png'), require('../res/emoji_smile/emoji_smile_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_sad.png"),
    "obj": require("../res/emoji_sad/emoji_sad.vrx"),
    "materials": null,
    "animation":null,
    "scale": [.2, .2, .2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_sad/emoji_sad_specular.png'), require('../res/emoji_sad/emoji_sad_diffuse.png'), require('../res/emoji_sad/emoji_sad_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_angry.png"),
    "obj": require("../res/emoji_angry/emoji_angry.vrx"),
    "materials": null,
    "animation":null,
    "scale": [0.2, 0.2, 0.2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_angry/emoji_angry_specular.png'), require('../res/emoji_angry/emoji_angry_diffuse.png'), require('../res/emoji_angry/emoji_angry_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_wow.png"),
    "obj": require("../res/emoji_wow/emoji_wow.vrx"),
    "materials": null,
    "animation":null,
    "scale": [0.2, 0.2, 0.2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_wow/emoji_wow_specular.png'), require('../res/emoji_wow/emoji_wow_diffuse.png'), require('../res/emoji_wow/emoji_wow_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_kiss.png"),
    "obj": require("../res/emoji_kiss/emoji_kiss.vrx"),
    "materials": null,
    "animation":null,
    "scale": [0.2, 0.2, 0.2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_kiss/emoji_kiss_specular.png'), require('../res/emoji_kiss/emoji_kiss_diffuse.png'), require('../res/emoji_kiss/emoji_kiss_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_heart.png"),
    "obj": require("../res/emoji_heart/emoji_heart.vrx"),
    "materials": null,
    "animation":null,
    "scale": [0.2, 0.2, 0.2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_heart/emoji_heart_specular.png'), require('../res/emoji_heart/emoji_heart.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_thumbsup.png"),
    "obj": require("../res/emoji_thumbsup/emoji_thumbsup.vrx"),
    "materials": null,
    "animation":null,
    "scale": [0.2, 0.2, 0.2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_thumbsup/emoji_thumbsup_specular.png'), require('../res/emoji_thumbsup/emoji_thumbsup_diffuse.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_poop.png"),
    "obj": require("../res/emoji_poop/emoji_poop.vrx"),
    "materials": null,
    "animation":null,
    "scale": [0.2, 0.2, 0.2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_poop/emoji_poop_specular.png'), require('../res/emoji_poop/emoji_poop_diffuse.png'), require('../res/emoji_poop/emoji_poop_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_pug.png"),
    "obj": require("../res/object_pug_animated/pug_animated.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.2, .2, .2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_pug_animated/pug_body_specular.png'), require('../res/object_pug_animated/pug_body_diffuse.png'), require('../res/object_pug_animated/pug_body_normal.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_cake.png"),
    "obj": require("../res/object_bday_cake/object_bday_cake.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.2, .2, .2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_bday_cake/object_cake_specular.png'), require('../res/object_bday_cake/object_cake_specular.png'), require('../res/object_bday_cake/object_cake_specular.png')],
  },
  {
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_object_flowers.png"),
    "obj": require("../res/object_flowers/object_flowers.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.2, .2, .2],
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/object_flowers/object_flowers_specular.png'), require('../res/object_flowers/object_flowers_specular.png'), require('../res/object_flowers/object_flowers_specular.png')],
  }
]

module.exports = {
  getInitModelArray: function() {
    return ModelItems;
  }
};
